### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by HoyoungParks** [sdzhao/cole#9]
Dear Professor Dave Zhao

Hi I am a PhD student who is very interested in your article.
So I tried to install your package and found the following error and have not solved it yet. May I get your advice?
To solve this problem, I tried also using devtools besides the remote command, but it did not solve the problem. Perhaps I guess there is a problem with the common installation path on github. I've attached the error I found on my computer below.
Thank you in advance for your sincerity. And have a nice day :)

Best wishes,
Hoyoung Park

> remotes::install_github("sdzhao/cole")
Downloading GitHub repo sdzhao/cole@master
Your system is ready to build packages!
✔  checking for file ‘/private/var/folders/dn/9pq4yfyd1j11cgp5v8qd8f1m0000gn/T/RtmpJHRqdP/remotesc23d2586169f/sdzhao-cole-94e1a96/DESCRIPTION’ (910ms)
─  preparing ‘cole’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (337ms)
─  checking for empty or unneeded directories
─  building ‘cole_1.1.0.tar.gz’
   
* installing *source* package ‘cole’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘cole’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/cole’
Error: Failed to install 'cole' from GitHub:
  (converted from warning) installation of package ‘/var/folders/dn/9pq4yfyd1j11cgp5v8qd8f1m0000gn/T//RtmpJHRqdP/filec23d63733f8/cole_1.1.0.tar.gz’ had non-zero exit status

FYI, my Rstudio version is :

> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes

**Comment by sdzhao** [comment]
Hi Hoyoung,

This issue appears to be related to the function comte() in the package. I just assigned it to the developer of comte(), and we will get back to you about this.

In the meantime, if you're interested in the other functions, you can check out the commits prior to July 9, 2018. However, as it turns out I'm about to update these other functions in the next week or so, so you might want to wait until then.

Thanks!

**Comment by pickyilkis** [comment]
Hi Hoyoung,

Here are a few ways to solve this problem:

### 1. change compiler
I assume that you are using MacOS. The compiler that comes with the OS is not compatible with Rcpp/RcppArmadillo during installation from source. [Here](https://thecoatlessprofessor.com/programming/r-compiler-tools-for-rcpp-on-macos-before-r-3.6.0/) is an article that addresses the issue. 

### 2. use a virtual machine 
I just tried with Ubuntu 18.04 in [virtual box](https://www.virtualbox.org/) and everything should work. 

### 3. docker(suggested)
If you want to do some experiment with `cole`, I suggest you to use a containerized environment. The building and running docker images functionalities are added into the repository.  Please follow the steps below:

- Install [docker](https://hub.docker.com/)
- In terminal, run `git clone https://github.com/sdzhao/cole.git` and then `cd cole`
- To build the image, type `./scripts/cole.sh build` 
- To run the container, type `./scripts/cole.sh r`
- In your browser, type `<your IP address>:8787` with username: `rstudio` and password `cole` you should be able to launch a Rstudio with `cole` installed.

**Comment by HoyoungParks** [comment]
> Hi Hoyoung,
> 
> Here are a few ways to solve this problem:
> 
> ### 1. change compiler
> I assume that you are using MacOS. The compiler that comes with the OS is not compatible with Rcpp/RcppArmadillo during installation from source. [Here](https://thecoatlessprofessor.com/programming/r-compiler-tools-for-rcpp-on-macos-before-r-3.6.0/) is an article that addresses the issue.
> 
> ### 2. use a virtual machine
> I just tried with Ubuntu 18.04 in [virtual box](https://www.virtualbox.org/) and everything should work.
> 
> ### 3. docker(suggested)
> If you want to do some experiment with `cole`, I suggest you to use a containerized environment. The building and running docker images functionalities are added into the repository. Please follow the steps below:
> 
> * Install [docker](https://hub.docker.com/)
> * In terminal, run `git clone https://github.com/sdzhao/cole.git` and then `cd cole`
> * To build the image, type `./scripts/cole.sh build`
> * To run the container, type `./scripts/cole.sh r`
> * In your browser, type `<your IP address>:8787` with username: `rstudio` and password `cole` you should be able to launch a Rstudio with `cole` installed.


Hello I apologize for the late reply.

As your advice I tried using docker as the third solution.
I did it from the beginning to the fourth in your instruction. 
( The following : )
Install docker
In terminal, run git clone https://github.com/sdzhao/cole.git and then cd cole
To build the image, type ./scripts/cole.sh build
To run the container, type ./scripts/cole.sh r

However,
 when I type <my IP address>:8787, I got an error saying that I can't connect to the server.
I checked my firewall and my internet browser firewall is turned off.
Should I install rstudio server at the address corresponding on my IP?
I am sincerely sorry to bother you and thank you in advance.
Have a nice day! 

Regards,
Hoyoung

**Comment by pickyilkis** [comment]
Hi Hoyoung,

I don't think you need to install rstudio server.
Few things we can check:

- What shows up in your terminal when you do  `./scripts/cole.sh r`?

- Can you see `cole/base` and `rocker/verse` if you type `docker images` in your terminal?

- Can you also try `localhost:8787`?

**Comment by HoyoungParks** [comment]
Hi
After retype `./scripts/cole.sh r` in terminal


I can access "localhost:8787" 
and everything is done.
Thank you for your consideration.
Have a nice day! :)

Regards,
Hoyoung.


FYI, I attached my output in the following 

> Hi Hoyoung,
> 
> I don't think you need to install rstudio server.
> Few things we can check:
> 
> * What shows up in your terminal when you do  `./scripts/cole.sh r`?

baghoyeongs-iMac:cole Ho-Young$ ./scripts/cole.sh r
Running R
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing... 
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing... 
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.




> * Can you see `cole/base` and `rocker/verse` if you type `docker images` in your terminal?

baghoyeongs-iMac:~ Ho-Young$ docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
cole/base            latest              e05456a2eb98        47 hours ago        3.28GB
hyparks/cheers2019   latest              ff8813f9bb79        47 hours ago        4.01MB
<none>               <none>              e0c26fbcab12        47 hours ago        356MB
rocker/verse         latest              31756fe80a6c        2 days ago          3.25GB
golang               1.11-alpine         e116d2efa2ab        2 weeks ago         312MB
baghoyeongs-iMac:~ Ho-Young$ 



> * Can you also try `localhost:8787`?
